In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [12]:
from sklearn import datasets

iris = datasets.load_iris()


In [13]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [14]:
cross_val_score(LinearRegression(),iris.data,iris.target)

array([0.        , 0.85124923, 0.        , 0.76155439, 0.        ])

In [15]:
cross_val_score(SVC(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [11]:
cross_val_score(RandomForestClassifier(n_estimators=40),irists.data,digits.target)

array([0.92777778, 0.90555556, 0.95543175, 0.96657382, 0.91643454])