In [5]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [6]:
df = pd.read_csv('hiring.csv')

In [7]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [8]:
df.experience =df.experience.fillna('zero')

In [9]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [10]:
df.experience = df.experience.apply(w2n.word_to_num) 
#convert word to number

In [11]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [12]:
import math
median_test_score = math.floor(df['test_score(out of 10)'].mean())

In [13]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_test_score)

In [14]:
re = linear_model.LinearRegression()

In [15]:
re.fit(df[["experience","test_score(out of 10)","interview_score(out of 10)"]],df["salary($)"])

LinearRegression()

In [16]:
re.predict([[2,9,6]])

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [17]:
import pickle


In [19]:
with open('re_pickle','wb') as f:
    pickle.dump(re,f)

In [20]:
with open('re_pickle','rb') as f:
    rp = pickle.load(f)

In [21]:
rp.predict([[2,9,6]])

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [25]:
 import joblib

In [26]:
joblib.dump(re,'model_joblib')

['model_joblib']

In [27]:
rj = joblib.load('model_joblib')

In [28]:
rj.predict([[2,9,6]])

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])